# Generated by Django 3.0.5 on 2020-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialLive',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='TIMESTAMP', primary_key=True, serialize=False)),
                ('verbr_kwh_181', models.FloatField(blank=True, db_column='VERBR_KWH_181', null=True)),
                ('verbr_kwh_182', models.FloatField(blank=True, db_column='VERBR_KWH_182', null=True)),
                ('gelvr_kwh_281', models.FloatField(blank=True, db_column='GELVR_KWH_281', null=True)),
                ('gelvr_kwh_282', models.FloatField(blank=True, db_column='GELVR_KWH_282', null=True)),
                ('tariefcode', models.TextField(blank=True, db_column='TARIEFCODE', null=True)),
                ('act_verbr_kw_170', models.FloatField(blank=True, db_column='ACT_VERBR_KW_170', null=True)),
                ('act_gelvr_kw_270', models.FloatField(blank=True, db_column='ACT_GELVR_KW_270', null=True)),
                ('verbr_gas_2421', models.FloatField(blank=True, db_column='VERBR_GAS_2421', null=True)),
            ],
        ),
    ]
